# General design
#seed = 1696298614598191000

canvas_size = 1600

primary_external_node_distance = 500 # this must be less than half of the canvas size
primary_internal_nodes_distance = 100 # radius of the internal circle

secondary_nodes_min_radius = 200
secondary_nodes_max_radius = 400

min_number_of_secondary_nodes = 11
max_number_of_secondary_nodes = 16
min_distance_between_nodes = 130
number_of_sectors_for_secondary_nodes = 12

min_number_of_links = 16 # this includes the initial *3* Links created as base
max_number_of_links = 24
min_links_per_node = 2
max_links_per_node = 5

# Drawing
primary_link_stroke_width = 9.0
secondary_link_stroke_width = 6.5 # in the original it was double the regular

primary_node_radius = 20.0 # primary node are filled in

secondary_node_radius = 20.0 # secondary Nodes have the same stroke_width, the outher radius is defined here
secondary_node_stroke_width = 6.5